includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser-full.yaml

variables:
  main: "./cmd/wishlist"
  description: "The SSH directory"
  github_url: "https://github.com/charmbracelet/wishlist"
  maintainer: "Carlos A Becker <carlos@charm.sh>"
  brew_commit_author_name: "Carlos A Becker"
  brew_commit_author_email: "carlos@charm.sh"
