#
# setup wishlist with a YAML file
#


# Address in which wishlist should listen for.
# Defaults to 0.0.0.0.
listen: 127.0.0.1

# Port in which wishlist should listen for.
# Defaults to 22 or 2222, whichever is open.
port: 2223

# Endpoints to list in the UI.
endpoints:
-
  # Endpoint's name.
  # Recommended to avoid spaces so users can `ssh -t appname`.
  name: appname

  # Endpoint's address in the host:port format.
  address: foo.local:2234

  # An URL to be printed in the list.
  # links:
  #   - name: GitHub
  #     url: https://github.com/charmbracelet/wishlist
  #
  # description: "single-line short description of this app."

  # User to use to connect.
  # Defaults to the current remote user.
  user: notme

  # Command to run against the remote address.
  # Defaults to asking for a shell.
  remote_command: uptime -a

  # Wether to forward the SSH agent.
  # Will cause the connection to fail if no agent is available.
  forward_agent: true # forwards the ssh agent

  # requests a TTY.
  # Defaults to true if remote_command is empty.
  request_tty: true

- name: another2
  address: foo.local:2235
  description: "another apps description.\nalala\naaaaaaaaaaaa"
- name: another
  address: foo.local:2235
  description: "another apps description."
  # links:
  #   - url: https://github.com/charmbracelet/wish
  #   - url: https://github.com/charmbracelet/wishlist

# users to allow access to the list
users:
  -
    # user login
    name: carlos

    # User's public keys.
    # Must be in the same format as seen in the ~/.allowed_keys file.
    public-keys:
    - ssh-rsa AAAAB3Nz...
    - ssh-ed25519 AAAA...

