#
# setup wishlist with a YAML file
#

# Address in which wishlist should listen for.
# Defaults to 0.0.0.0.
listen: 127.0.0.1

# Port in which wishlist should listen for.
# Defaults to 22 or 2222, whichever is open.
port: 2223

# Endpoints to list in the UI.
endpoints:
  - #

    # Endpoint's name.
    # Recommended to avoid spaces so users can `ssh -t thename`.
    name: thename

    # Endpoint's address in the host:port format.
    address: foo.local:2234

    # A descripton of the item.
    description: "A description of this endpoint.\nCan have multiple lines."

    # User to use to connect.
    # Defaults to the current remote user.
    user: notme

    # Command to run against the remote address.
    # Defaults to asking for a shell.
    remote_command: uptime -a

    # Whether to forward the SSH agent.
    # Will cause the connection to fail if no agent is available.
    forward_agent: true # forwards the ssh agent

    # Requests a TTY.
    # Defaults to true if remote_command is empty.
    request_tty: true

    # Connection timeout.
    connect_timeout: 10s

    # Connect to the host through this proxy.
    proxy_jump: "user@host:22"

    # An URL to be printed in the list.
    link:
      name: Optional link name
      url: https://github.com/charmbracelet/wishlist

    # IdentityFiles to try to use to authorize.
    # Only used in local mode.
    identity_files:
      - ~/.ssh/id_rsa
      - ~/.ssh/id_ed25519

    # Set environment variables into the connection.
    # Analogous to SSH's SetEnv.
    set_env:
      - FOO=bar
      - BAR=baz

    # Environments from the environment that match these keys will also be set
    # into the connection.
    # Analogous to SSH's SendEnv.
    # Defaults to ["LC_*", "LANG"].
    send_env:
      - LC_*
      - LANG
      - SOME_ENV

# Hints can be used to hint settings into discovered endpoints.
#
# You can use it to change the user, port, set remote commands, etc.
#
# A host can match multiple hints, in which all matched hints will be applied,
# the last one having the priority.
hints:
  - #
    # Glob to be used to match the discovered names.
    match: "*.local"

    # SSH port to use.
    port: 23234

    description: "A description of this endpoint.\nCan have multiple lines."
    user: notme
    remote_command: uptime -a
    forward_agent: true
    request_tty: true
    connect_timeout: 10s
    proxy_jump: "user@host:22"
    link:
      name: Optional link name
      url: https://github.com/charmbracelet/wishlist
    identity_files:
      - ~/.ssh/id_rsa
      - ~/.ssh/id_ed25519
    set_env:
      - FOO=bar
      - BAR=baz
    send_env:
      - LC_*
      - LANG
      - SOME_ENV

# Users to allow access to the list
users:
  - # User login
    name: carlos

    # User's public keys.
    # Must be in the same format as seen in the ~/.allowed_keys file.
    public-keys:
      - ssh-rsa AAAAB3Nz...
      - ssh-ed25519 AAAA...

# Setup the /metrics prometheus endpoint.
metrics:
  # Enable the metrics.
  enabled: true

  # App name that will be used in the metrics.
  name: my-wishlist

  # Address to bind to.
  address: localhost:9223
